### ISSUE TITLE
Brand "Create new" missing

### ISSUE THREAD

**Issue by JojinoS** [OCA/brand#160]
Hi, tested this module, seems all is OK, except a fact that if I go here : "Go to Sales > Configuration > Products > Product Brands.
I dont have any Button to click on to "create new Brand....

1.Go to Sales App/Configuration/Products/Product brand
2. see the empty list, do not have button to create new brand

ODOO V16, EE, on premise, hosted on Ubuntu, almost empty with no user data.
![brand](https://user-images.githubusercontent.com/16004159/218535398-8014dfbd-8caf-474f-9a94-0c96e998b0ef.png)

**Comment by Neseef** [comment]
facing same issue. odoo16 on premise. 

1. Sales module installed,
2. product brand manager installed
3. then went to Sales App/Configuration/Product brand

gave me the same window as in the question. Blank page without a button to create new.
(Note: Maybe related, Not using default Odoo theme)

**Comment by metaminux** [comment]
This is due to Access Rights only giving Create, Write and Delete permissions to "Contact creation" group (base.group_partner_manager)

See https://github.com/OCA/brand/blob/1eca8ad74ca22b417b37c4b3ec305c2b471bdafb/product_brand/security/ir.model.access.csv?plain=1#L2

This is really old... but it used to be the product.group_product_manager originally (see https://github.com/OCA/product-attribute/commit/435aaa7e1d455dad400b68e8d7433419397e3e99#diff-ee0f6b18e0068a57b8d7056a6ef8f036f5508a19c9adcc952c9ffc2ff11042c0)
