### ISSUE TITLE
[RFC] - brand modules name and model name

### ISSUE THREAD

**Issue by sbejaoui** [OCA/brand#8]
Hi,

As a first step when we moved the brand modules to this new repository, I proposed #5 to have a separate model for brands and not use the `res.partner`.

As this refactoring is about to join the 12.0 and some questions are still outstanding and it's time to make a decision on these aspects before moving forward.

The main topics, I remember, we raised were:
- modules name:
   - why not have base_brand instead of partner_brand? by @levkar [link](https://github.com/OCA/brand/pull/5#issuecomment-529482029)
   - What about sale_company_branding or sale_company_brand? by @pedrobaeza  [link](https://github.com/OCA/brand/pull/3#issuecomment-527509170)
- model name for brand
   - Why not simply brand? by @sbidoul [link](https://github.com/OCA/partner-contact/issues/765#issuecomment-522219566)

1- What do you think about this proposals? 
2- Do you approve this changes?
3- Should we made this changes ASAP or we can keep them in the roadmap?

Kind regards.

cc/ @max3903 , @rafaelbn , @gva-acsone

**Comment by sbejaoui** [comment]
For me, modules name should be like \*company_brand\* to clarify the difference with the product brand. @rafaelbn explained it well in #4 .

I proposed `res.brand` because I think it's an acronym for "company resources". In the same context, there are `res.company`, `res.users`, `res.partner` and I think that the company brands are part of this logic.

**Comment by levkar** [comment]
There are 2 paths to follow in my opinion.

1) keep all brand stuff together here in this repo:
then we need one brand model (can be a base module with base_brand) and all modules extend that base model. Company modules can be renamed with prefix/postfix "company_brand" so that they don't get confused with product brand.

2) have two different repos:
- for product branding
- for company brand management (names of the modules are better start with "sale_brand" "company_brand" or something like that)

As it is right now, this repo name is confusing.

**Comment by rafaelbn** [comment]
I would like to receive more opinions like @willArrive @yvaucher @LeartS @pedrobaeza @JayVora-SerpentCS @bguillot @chienandalu 

In my opinion one/this this repo is enough for all modules around brands. Because even thought we have to different scenarios, both scenarios could occur at the same time ( Scenarios: https://github.com/OCA/brand/issues/4 )

So :+1: single repo

About

> modules name should be like *company_brand* to clarify the difference with the product brand

:+1:  When I saw the modules sale_brand and partner_brand I misunderstood the objective of the modules

About other things I think you should make what is in budget, the rest in the roadmap for v13

My wishlist about all of this is that the model brand could be used for partner or for products in the way that as I said both scenarios could live together and use the same resources. But this is a big work as would change the original product_brand.
